name: Benchmarks

on: push

jobs:
  test:
    name: Send metric over UDP
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1

    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: 3.1
        bundler-cache: true

    - name: Run benchmark on branch
      run: benchmark/send-metrics-to-local-udp-receiver

    - name: Run throughput benchmark on branch
      run: benchmark/local-udp-throughput

    - uses: actions/checkout@v1
      with:
        ref: 'master'

    - name: Install dependencies if needed
      run: bundle check || bundle install --jobs 4 --retry 3

    - name: Run benchmark on master
      run: benchmark/send-metrics-to-local-udp-receiver

    - name: Run throughput benchmark on master
      run: benchmark/local-udp-throughput
